#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set DP-4 as the primary monitor
bspc monitor DP-4 -d I II III IV

# Set HDMI-0 as the secondary monitor
bspc monitor HDMI-0 -d I II III IV

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_action_interval 1

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Set border colors
bspc config normal_border_color "#1e1e2e"  # Unfocused window border color
bspc config active_border_color "#1e1e2e"  # Focused window border color on unfocused monitor
bspc config focused_border_color "#f2cdcd"  # Focused window border color on focused monitor

lxsession&
bash /home/weescottishman/.config/polybar/polybar.sh &
feh --bg-scale /home/weescottishman/Pictures/Wallpaper.jpeg

